import type { NextPage } from 'next';
import Head from 'next/head';
import Router from 'next/router';
import { useEffect } from 'react';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  useEffect(() => {
    Router.push({ pathname: '/yellowlist' });
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Yellow</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
